version: "3.9"

services:
  db:
    image: postgis/postgis:14-3.3-alpine
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: "osm"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    restart: on-failure

  app:
    build: .
    env_file:
      - ".env"
    depends_on:
      - db
    ports:
      - "5000:8000"

volumes:
  pg_data: