[tool.isort]
lines_after_imports = 2
multi_line_output = 3
use_parentheses = true
force_sort_within_sections = true
include_trailing_comma = true
ensure_newline_before_comments = true
lexicographical = true
group_by_package = true
skip = [
  '.git',
  '.venv',
  'venv',
  'migrations',
  '__pycache__',
  '.pytest_cache',
  '__init__.py',
  ]


[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
(
    /(
        |\.git
        |venv
        |\.venv
        |migrations
        |__init__\.py
        |__pycache__
        |\.pytest_cache
        |postgis
    )/
)
'''