"""initial

Revision ID: 51af57bcbcc5
Revises: 
Create Date: 2022-12-09 22:30:21.890114

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

from app.utils.parse import insert_data

# revision identifiers, used by Alembic.
revision = '51af57bcbcc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    location = op.create_table(
        'location',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('location', sa.String(), nullable=False),
        sa.Column('point', geoalchemy2.types.Geometry(geometry_type="POINT", srid=4326), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        location,
        insert_data(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    # ### end Alembic commands ###
